### ISSUE TITLE
Classname APIs for items

### ISSUE THREAD

**Issue by rolfsmeds** [vaadin/platform#4748]
## Description
CSS classname APIs for items within components:
- Grid header and footer cells
- Menu items
- Message List items (messages)
- Avatar Group items (avatars)
- Select items

## Use cases
As a developer
I want to apply CSS classnames to specific items
So that I can style them individually

## Acceptance criteria
- [x] [Grid header and footer cell classname API](https://github.com/vaadin/web-components/issues/1434)
- [x] [Message List item classname API](https://github.com/vaadin/web-components/issues/5335)
- [x] [Context Menu item classname API](https://github.com/vaadin/web-components/issues/5341)
- [x] [Menu Bar item classname API](https://github.com/vaadin/web-components/issues/5342)
- [x] [Select dropdown item classname API](https://github.com/vaadin/web-components/issues/6616)
- [x] [Avatar Group item classname API](https://github.com/vaadin/web-components/issues/5344)

## General criteria
- [x] APIs reviewed 
- [x] UX/DX tests in Alpha 
- [ ] Documentation: To be added to documentation pages of individual components

## Security
- [x] Security implications have been taken into account (elaborate or link to product security requirement specification if there are implications)
