### ISSUE TITLE
Specify minimum versions for NPM

### ISSUE THREAD

**Issue by ripla** [vaadin/platform#515]
### Problem
It has turned out that locking dependency versions, e.g. `vaadin-text-field` 1.2.3 for `npm` in a platform release is way too restrictive to be useful in practice. When the text field version is locked to 1.2.3, you will immediately end up with duplicate versions of the component if you add another component which requires a newer (or older) version of text-field. Today this happens e.g. if you try to use the latest `vaadin-login` alpha with Vaadin 12 as `vaadin-login` requires `vaadin-text-field` `2.3.0-alpha3` or newer but Vaadin 12 defines `vaadin-text-field` 2.1.5 should be used. `npm` happily deals with this by installing two versions and the project is broken

### Solution
Starting from Vaadin 13, we will no longer lock the versions for `npm` in the platform. All dependencies are specified as minimum version required, allowing all newer patch and minor versions to be used. We will instead provide a version lock file for the starters so that the application builds are repeatable. We will encourage users to include a lock file in their projects also to avoid surprising dependency updates when a new version of something is released

### Tasks
- [x] Change npm releases to use `^` instead of exact versions
- [x] Create an npm shrinkwrap for `vaadin` and `vaadin-core` when releasing
- [x] Separately release `@vaadin/vaadin`, `@vaadin/vaadin-shrinkwrap`, `@vaadin/vaadin-core` and `@vaadin/vaadin-core-shrinkwrap`
- [x] Update repository readme with information about npm releases
- [x] Update V13 starters to use shrinkwrap dependencies

**Comment by ripla** [comment]
This is a superset of https://github.com/vaadin/platform/issues/495

**Comment by Artur-** [comment]
Does this mean that you would depend on `@vaadin/vaadin-shrinkwrap` instead of `@vaadin/vaadin` if you want it to use specific versions? 

Do those versions defined in a shrinkwrap for `@vaadin/vaadin-shrinkwrap` really affect transitive dependencies also or will it only cause a specific version of e.g `vaadin-button` to be installed inside `node_modules/@vaadin/vaadin/node_ modules`, which is not what you want? Say e.g. that `vaadin-grid` depends on a version range of `vaadin-button`, will it get another version and the whole shrinkwrap becomes useless? @web-padawan

**Comment by web-padawan** [comment]
Follow-up to the question above, summarising the current effort:

1. two packages to be released:
- `@vaadin/vaadin-core-shrinkwrap` will be released for each `@vaadin/vaadin-core` release
- `@vaadin/vaadin-shrinkwrap` will be released for each `@vaadin/vaadin` release

2. Latest (at the time of running `npm publish`) patch and minor releases of web components are picked up and pinned so that users can be sure about versions they install

3. Duplicate dependencies should not happen as long as user does not attempt to install unexpected version by himself - e.g. install different version of `@polymer/polymer`, say 3.2.0, while 3.1.0 is pinned by the shrinkwrap

4. Any minor and patch release of `@polymer/polymer` and `@polymer/iron-*` we use should be updated as fast as possible, to make sure the situation described by 3. never really happens

**Comment by web-padawan** [comment]
Looks like `npm dedupe` will be still needed to make proper use of the shrinkwrap.

See vaadin/generator-polymer-init-vaadin-elements-app#28

**Comment by ripla** [comment]
Info available in release notes, under Getting Started Manually.
